### ISSUE TITLE
Using the resource when the target execution policy is Restricted

### ISSUE THREAD

**Issue by rosberglinhares** [PowerShell/xPowerShellExecutionPolicy#10] opened 2017-07-12 17:42 UTC
When I execute this resource in a Restricted exectution policy environment, I get this error:

>Importing module MSFT_xPowerShellExecutionPolicy failed with error - File C:\Program Files\WindowsPowerShell\Modules\xPowerShellExecutionPolicy\1.1.0.0\DscResources\MSFT_xPowerShellExecutionPolicy\MSFT_xPowerShellExecutionPolicy.psm1 cannot be loaded because running scripts is disabled on this system

Is it possible to use this resource when the target execution policy is Restricted? Can we overcome the Chicken and Egg problem?

**Comment by 4c74356b41** [comment] 2017-07-25 10:34
Funny, stumbled upon this issue. whats the use of this if its a script? sigh

**Comment by johlju** [comment] 2018-04-24 05:44
Sorry that nobody responded earlier. Can you provide the DSC configuration you are using (obfuscate any sensitive information), also the OS and the PowerShell version on the target node.

**Comment by TraGicCode** [comment] 2018-05-04 20:01
@johlju , I understand what he is saying and there is really no good solution.  Essentially if you tell powershell to be super strict on execution policy settings you lock yourself out of using dsc to execute powershell.

**Comment by johlju** [comment] 2018-05-04 20:08
By default Windows Server is not configured that restricted, am I right? So that setting must first be set stricter by other means? 

Could we say that this is by design?

**Comment by 4c74356b41** [comment] 2018-05-04 20:11
@johlju you can say anything, but by default this module doesnt work on Azure VMs. If thats intended - I accept that, I have my workaround, but, well, thats yet another shitty "solution" from microsoft

**Comment by johlju** [comment] 2018-05-05 13:39
I have tried to reproduce this issue, but couldn't. I get the configuration to run. When deploying a fresh Windows Server 2016 and Windows Server 2012 R2 the execution policy is default set to `RemoteSigned`. Running the following script will set the configuration to `Unrestricted` without any problems.

```powershell
xPowerShellExecutionPolicy ExecutionPolicy
{
    ExecutionPolicy      = 'Unrestricted'
    ExecutionPolicyScope = 'LocalMachine'
}
```

If manually setting the execution policy to `Restricted` the script that validates the compliancy fails (as expected) as seen in the image below, but once the configuration runs and restores the execution policy the script can successfully run again.

![image](https://user-images.githubusercontent.com/7189721/39663746-2606d806-5079-11e8-86d8-993e1e4215c9.png)

Maybe the problem was that before, when this issue was raised, the default was `Restricted` but that doesn't seem to be the case today.

**Comment by johlju** [comment] 2018-05-10 10:52
Closing this issue as this does not seem to be a problem any longer. If someone encounters this, please comment and provide the configuration and the environment where this is happening.

**Closed by johlju** 2018-05-10 10:52 UTC
Labels: needs more information, question
